import './globals.css'
import { Roboto } from 'next/font/google'
import Toaster from '@/components/Toaster'

const roboto = Roboto({ weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es'>
      <Toaster />
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
